# Generated by Django 5.2.3 on 2025-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(null=True)),
                ('reviews_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wb_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['price'], name='products_price_fe467e_idx'), models.Index(fields=['rating'], name='products_rating_53cb37_idx'), models.Index(fields=['reviews_count'], name='products_reviews_ce1319_idx'), models.Index(fields=['created_at'], name='products_created_e1ba5f_idx')],
            },
        ),
    ]
